services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    logging:
      driver: "json-file"
      options:
        max-size: "100k"

  api:
    image: ghcr.io/nquidox/api-task:latest
    depends_on:
      - postgres
    env_file:
      - secrets.env
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
    restart: unless-stopped

  postgres:
    image: postgres:17.2
    volumes:
      - ./temp/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=789superpass
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
    restart: unless-stopped
