# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Makepkg

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23.x
      - uses: actions/checkout@v4
      - run: go test ./...

      - name: go vet
        run: go vet ./...



  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin v1.63.4
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Verify golangci-lint installation
        run: golangci-lint --version

      - name: Run golangci-lint
        run: golangci-lint run ./...


  build:
    name: Build container
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        
      - name: Building container image and push to hub
        run: |
          docker buildx build --push \
            --tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} \
            --tag ghcr.io/${{ github.repository }}:latest .
